INSERT INTO CAR(ID, MODEL , BRAND, COLOR, CREATEDDATE) VALUES (1, 'MUSTANG', 'FORD', 'BLACK', '2019-10-11');
INSERT INTO CAR(ID, MODEL , BRAND, COLOR, CREATEDDATE) VALUES (2, 'TOLEDO', 'SEAT', 'GREY', '1999-10-11');
